apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: fjernlys-api
  namespace: fjernlys
  labels:
    team: fjernlys
spec:
  image: {{ image }}
  port: 8080
  replicas:
    cpuThresholdPercentage: 90
    min: 1
    max: 1
  liveness:
    initialDelay: 30
    path: /internal/isalive
  readiness:
    initialDelay: 30
    path: /internal/isready
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 400m
      memory: 512Mi
  ingresses:
    - https://fjernlys-api.ekstern.dev.nav.no
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: "fjernlys-api-db"
            envVarPrefix: DB
  accessPolicy:
    inbound:
      rules:
        - application: fjernlys
